version: '3'

services:

  # database containers, one for each db
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - /srv/db_vaga_dev:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - database
    ports:
      - "5432:5432"

  # web container, with django + gunicorn
  djangoapp:
    build:
      context: .
      dockerfile: DockerfileDEV
    environment:
      - DJANGO_SETTINGS_MODULE
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - database
    ports:
      - "8000:8000"
    depends_on:
      - db


networks:
  database:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  static:
  media:
